version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: post
      POSTGRES_PASSWORD: post
      POSTGRES_DB: articles
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --requirepass authpassword
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: post
      PG_PASS: post
      PG_NAME: articles

      JWT_ACCESS_TOKEN_KEY: 123
      JWT_UPDATE_TOKEN_KEY: 321

      REDIS_URL: redis://:authpassword@redis:6379/
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
  redisdata:
